### ISSUE TITLE
Failed to checkout tag: 'v0.5.0'

### ISSUE THREAD

**Issue by shomedas** [pezcode/open3d-core-android#2]
Hi I am trying to build on ubuntu 16.04.  i get error Failed to checkout tag: 'v0.5.0'. How can i fix it?
cmake version 3.5.1
git version 2.20.1

cmake --build .
[2/40] Performing download step (git clone) for 'open3d-fetch'
FAILED: cd /home/shome/temp_codes/open3d_android/open3d-core-android/build/CMakeExternals/Source && /usr/bin/cmake -P /home/shome/temp_codes/open3d_android/open3d-core-android/build/CMakeExternals/tmp/open3d-fetch/open3d-fetch-gitclone.cmake && /usr/bin/cmake -E touch /home/shome/temp_codes/open3d_android/open3d-core-android/build/CMakeExternals/Stamp/open3d-fetch/open3d-fetch-download
Cloning into 'origin'...
CMake Error at /home/shome/temp_codes/open3d_android/open3d-core-android/build/CMakeExternals/tmp/open3d-fetch/open3d-fetch-gitclone.cmake:49 (message):
  Failed to checkout tag: 'v0.5.0'

ninja: build stopped: subcommand failed.

**Comment by pezcode** [comment]
I got a similar (but not quite the same) error using your version of CMake and Git which was caused by the `GIT_SHALLOW` option:
> error: pathspec 'true' did not match any file(s) known to git

You can try removing [line 56](https://github.com/pezcode/open3d-core-android/blob/1c4a6cfd5531eabb3c853f9002a4bfd537c3003e/CMakeLists.txt#L56) from CMakeLists.txt.

Before you do that, consider upgrading CMake to 3.6 or higher. `GIT_SHALLOW` is supported in that CMake version and it's also the minimum version required by the Android NDK. So you'll most likely have to upgrade anyway unless you want to use a custom NDK CMake toolchain.

**Comment by shomedas** [comment]
Your suggestion worked. updating git & cmake helped me solve the problem

**Comment by pezcode** [comment]
Glad to hear.
